const mySpots = [
  [
    "Coffeemania Kırklareli",
    41.73145,
    27.21542,
    "Premium Kafe",
    "İstasyon Caddesi'nin girişinde, geniş terasıyla şehrin kalbinde prestijli bir çalışma alanı.",
    "₺₺",
    ["images/coffeemania1.webp", "images/coffeemania2.jpeg"],
    [
      "🚬 Isıtmalı Teras",
      "☕ Nitelikli Kahve",
      "🔌 Bol Priz",
      "📶 Hızlı Wi-Fi",
    ],
  ],
  [
    "David People Coffee",
    41.73180473145578,
    27.216140028444013,
    "Sosyal Alan",
    "Karakaş Mahallesi'nin en hareketli köşesi. Geniş bahçesi ve modern atmosferiyle tam bir buluşma noktası.",
    "₺₺₺",
    ["images/david1.webp", "images/david2.webp"],
    [
      "🍃 Dev Bahçe",
      "🚬 Sigara İçilebilir",
      "🍰 Gurme Tatlılar",
      "📸 Şık Tasarım",
    ],
  ],

  [
    "Sefa Köftecisi",
    41.73512,
    27.22234,
    "Tarihi Lezzet",
    "Kırklareli'nin sembolü. Arasta Çarşısı civarında, gerçek Kırklareli köftesini tadabileceğiniz en elit yer.",
    "₺₺",
    ["images/sefa1.webp"],
    ["🥩 Meşhur Köfte", "🥗 Yan Lezzetler", "🚭 Aile Ortamı", "🕰️ Nostaljik"],
  ],

  [
    "KÜ Merkez Kütüphane",
    41.7355,
    27.225,
    "Sessiz Alan",
    "Şehir merkezindeki kampüs içerisinde, tam odaklanma ve sınav maratonları için tasarlanmış sessiz bölge.",
    "Ücretsiz",
    ["images/kutuphane1.webp"],
    ["📚 Tam Sessizlik", "❄️ Klimalı", "💧 Su İstasyonu", "🚫 Sigara Yasak"],
  ],
  [
    "L’Avenue",
    41.73252,
    27.21448,
    "Premium Kafe",
    "İstasyon Caddesi'nin en şık duraklarından. Hem ders çalışmak hem de kaliteli kahve içmek için nokta atışı.",
    "₺₺",
    ["images/lavenue1.webp"],
    [
      "☕ Nitelikli Kahve",
      "🚬 Isıtmalı Dış Alan",
      "🛋️ Rahat Koltuklar",
      "📶 Hızlı Wi-Fi",
    ],
  ],
];
